server:
  port: 9092
spring:
  application:
    name: bookchain
  datasource:
    url: jdbc:mysql://localhost:3306/bookchainDB?createDatabaseIfNotExist=true
    username: root 
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      
  mvc:
    view:
      prefix: /
      suffix: .jsp
      
  messages:
    basename: validation
